name: Custom Workflow

on:
  workflow_dispatch:  # Enables manual trigger


jobs:
  action1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action 1
        run: echo "Executing Action 1"
             exit 1  # Force failure

  action2:
    runs-on: ubuntu-latest
    needs: action1
    steps:
      - name: Run Action 2
        run: echo "Executing Action 2"

  action3:
    runs-on: ubuntu-latest
    needs: [action1, action2]
    if: success()
    steps:
      - name: Run Action 3
        run: echo "Executing Action 3"

  action4:
    runs-on: ubuntu-latest
    needs: [action1, action2]
    if: failure()
    steps:
      - name: Run Action 4
        run: echo "Executing Action 4"

  action5:
    runs-on: ubuntu-latest
    needs: [action3, action4]
    if: failure()
    steps:
      - name: Run Action 5
        run: echo "Executing Action 5"
