name: Custom Workflow

on:
  workflow_dispatch:  # Enables manual trigger


jobs:
  action1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Action 1
        run: echo "Executing Action 1"
  action2:
    runs-on: ubuntu-latest
    needs: action1
    steps:
      - name: Run Action 2
        run: echo "Executing Action 3"


  action3:
    runs-on: ubuntu-latest
    needs: [action1, action2]
    if: success()
    steps:
      - name: Run Action 3
        run: echo "Executing Action 4"

  action4:
    runs-on: ubuntu-latest
    needs: [action1, action2]
    if: failure()
    steps:
      - name: Run Action 4
        run: exit 1  # Force failure


  action5:
    runs-on: ubuntu-latest
    needs: [action3, action4]
    if: failure() && (needs.action3.result == 'failure' || needs.action4.result == 'failure')
    steps:
      - name: Run Action 5
        run: echo "Executing Action 5"

